name: Create Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy via API
      run: curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.APP_DEPLOY_TOKEN }}" "https://api.digitalocean.com/v2/apps/${{ secrets.APP_ID }}/deployments"
